name: Unit Test Suite
on: push

jobs:
    unit-tests:
        name: PHPUnit test suite with PHP ${{ matrix.php }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: ['7.3', '7.4']

        steps:
            # Setup
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: PHP setup
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: mbstring, xml, ctype, iconv, intl
                    coverage: xdebug

            # Cache Composer dependencies
            -   name: Get composer cache directory
                id: composer-cache
                run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            -   name: Cache dependencies
                uses: actions/cache@v1
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
                    restore-keys: ${{ runner.os }}-composer-

            -   name: Install dependencies
                run: composer install --prefer-dist

            # Run tests suite
            -   name: Run test suite
                run: php vendor/bin/simple-phpunit --coverage-text
