name: Bundle installation
on: push

jobs:
    integration-tests:
        name: Installation in Symfony ${{ matrix.symfony }} with PHP ${{ matrix.php }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: ['7.4', '8.0']
                symfony: ['4.4', '5.0', '5.1', '5.2', '5.3']
                exclude:
                    - php: '8.0'
                      symfony: '5.0'

        steps:
            # Setup
            -   name: Checkout
                uses: actions/checkout@v2
                with:
                    path: 'project'

            -   name: PHP setup
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: mbstring, xml, ctype, iconv, intl
                    coverage: xdebug

            # Install symfony app
            -   name: Create Symfony app
                run: |
                    composer create-project symfony/skeleton:"${{ matrix.symfony }}.*" app
                    composer require -d ./app sensio/framework-extra-bundle symfony/twig-pack
                    composer config -d ./app repositories.commonmark-bundle path ../project
                    composer config -d ./app minimum-stability dev

            # Cache Composer dependencies
            -   name: Get composer cache directory
                id: composer-cache
                run: echo "::set-output name=dir::$(composer config -d ./app cache-files-dir)"

            -   name: Cache dependencies
                uses: actions/cache@v1
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
                    restore-keys: ${{ runner.os }}-composer-

            # Install the bundle
            -   name: Install AymdevCommonmarkBundle
                run: |
                    cp ./project/.github/fixtures/IntegrationController.php ./app/src/Controller/IntegrationController.php
                    cp ./project/.github/fixtures/integration.html.twig ./app/templates/home.html.twig
                    cp ./project/.github/fixtures/bundle_config.yaml ./app/config/packages/aymdev_commonmark.yaml
                    composer require -d ./app --prefer-source aymdev/commonmark-bundle:"*"

            # check homepage content
            -   name: Check application homepage status
                run: |
                    [[ $(php ./app/public/index.php) == "<h1>test</h1>" ]] || exit 1
